version: '3.8'

# Production overrides for docker-compose.yml
# Usage: docker-compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  openresume-api:
    # Production-specific environment variables
    environment:
      - NODE_ENV=production
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=5000
      - LOG_LEVEL=INFO
    
    # Remove development volumes, use production paths
    volumes:
      - /etc/openresume/config.json:/app/config.json:ro
      - /var/log/openresume:/app/logs
      - /var/lib/openresume/output:/app/output
    
    # Production resource limits
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: unless-stopped
        max_attempts: 3
    
    # Production logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security settings
    security_opt:
      - no-new-privileges:true
    read_only: false
    tmpfs:
      - /tmp
      - /app/temp